# Generated by Django 4.1.2 on 2022-10-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Xiaomi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smarthpones',
            new_name='Smartphones',
        ),
    ]
